### ISSUE TITLE
commit edrn & mcl into different branches of labcas, add gitignore

### ISSUE THREAD

**Issue by yuliujpl** [EDRN/labcas-ui#201]
## 🤔 Tell Us About the Feature

Replace this with a clear and concise description of the problem you're tying to solve; for example: I'm frustrated when … or I wish it were easier to …

## 🎇 What Solution You'd Like

Here, put a clear and concise description of what you want to happen.

## 〽️ Alternative Ideas

If you'd like, put in a description of any alternative solutions or features you've considered.

**Comment by yuliujpl** [comment]
Done for mcl but edrn running into this large file >100mb issue that I'm trying to resolve!

**Comment by nutjob4life** [comment]
FYIl I don't see the "mcl" branch when visiting https://github.com/EDRN/labcas-ui/branches/all:

<img width="195" height="309" alt="Image" src="https://github.com/user-attachments/assets/bd52eb54-796d-458f-9805-337d86365ff6" />

**Comment by hoodriverheather** [comment]
@yuliujpl and @nutjob4life Can this be closed?

**Comment by nutjob4life** [comment]
@hoodriverheather  wrote:

> Can this be closed?

I don't think so. I still don't see `edrn` or `mcl` (or `nist`) branches when visiting https://github.com/EDRN/labcas-ui/branches/all

If the UI code for all three has converged, then yes. But so far as I know, the UI is different for each consortium, and so each consortium should have its own branch in GitHub so that changes can be tracked, configuration controlled, and catastrophic loss avoided.
