### ISSUE TITLE
Modify text on login screen for Forgot password link

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/labcas-ui#217]
## 🤔 Tell Us About the Feature
@yuliujpl Can you update the text on the login screen under the Non-EDRN member. Please change:
[Forgot](https://edrn-labcas.jpl.nasa.gov/biokey/edrn/forgotten/) your password to ready Forgot your password and/or your username

**Comment by yuliujpl** [comment]
Done in dev!
________________________________
From: hoodriverheather ***@***.***>
Sent: Wednesday, July 10, 2024 12:44 PM
To: EDRN/labcas-ui ***@***.***>
Cc: Liu, David (US 3902-Affiliate) ***@***.***>; Assign ***@***.***>
Subject: [EXTERNAL] Re: [EDRN/labcas-ui] Modify text on login screen for Forgot password link (Issue #217)


Assigned #217<https://urldefense.us/v3/__https://github.com/EDRN/labcas-ui/issues/217__;!!PvBDto6Hs4WbVuu7!L-4JPRNe6-wuspzTgvApELYUU38CJ1ZKJKmSGGe7-075oLrdfsJPaikxl6PoJ-R7YPoLECb7lfe0BGEeHbzCE-cYip3C2g$> to @yuliujpl<https://urldefense.us/v3/__https://github.com/yuliujpl__;!!PvBDto6Hs4WbVuu7!L-4JPRNe6-wuspzTgvApELYUU38CJ1ZKJKmSGGe7-075oLrdfsJPaikxl6PoJ-R7YPoLECb7lfe0BGEeHbzCE-dUpaF8sw$>.

**Comment by hoodriverheather** [comment]
@yuliujpl Thanks for putting this in dev. I'm realizing it's very long. Could you make this a summary and then click more to see more details? that way it doesn't take up as much space on the login page, but still gets attention?

Summary wording: 
**Announcement: Update to EDRN Data Access

Public EDRN data holdings can still be browsed without LabCAS credentials. To view or download file metadata and data, user registration is now required for enhanced security. Click to learn more.**

Then the entire announcement can be under the click more:
We are implementing an important update regarding access to EDRN data holdings. Users can still browse and explore EDRN data holdings that are publicly available without LabCAS credentials.

To enhance security and manage data access more effectively, user registration is required to view or download publicly available file metadata and data.

How to Access:
Non-EDRN Members/Research Community:

[Apply](https://edrn-labcas.jpl.nasa.gov/biokey/edrn/sign-up/) for an account

EDRN Members:

[Apply](https://www.compass.fhcrc.org/edrns/pub/user/application.aspx?t=app&sub=form1&w=1&p=3) for an account
[Reset or change](https://www.compass.fhcrc.org/edrns/pub/user/resetPwd.aspx?t=pwd&sub=form&w=1&p=3) your password

We appreciate your understanding and cooperation with this new requirement. If you have any questions or need assistance, please contact the [Informatics Center](mailto:edrn-ic@jpl.nasa.gov).

**Comment by hoodriverheather** [comment]
@yuliujpl I meant to put this under https://github.com/EDRN/labcas-ui/issues/216 Do you want me to move it?

**Comment by yuliujpl** [comment]
Done in Dev!

**Comment by hoodriverheather** [comment]
@yuliujpl Looks great! Can you push to prod?

**Comment by yuliujpl** [comment]
@hoodriverheather  pushed to edrn-labcas prod. Can you check?

**Comment by hoodriverheather** [comment]
@yuliujpl I don't see the updated login text under the Non-EDRN member on Prod.
[Forgot](https://edrn-labcas.jpl.nasa.gov/biokey/edrn/forgotten/) your password to ready Forgot your password and/or your username.
<img width="1412" alt="Screenshot 2024-07-22 at 9 48 47 AM" src="https://github.com/user-attachments/assets/11e69034-4e12-4eb1-ad28-d88cfe1b6e37">

I see it on Dev. Can you please push this update to Prod?
<img width="1453" alt="Screenshot 2024-07-22 at 9 48 22 AM" src="https://github.com/user-attachments/assets/4d46c1f4-f8fa-4c6e-9656-3afddbb2fc7f">

**Comment by yuliujpl** [comment]
Done! Also, labcas prod is now updated with the download option. Please let me know if downloading works for linux and windows!
________________________________
From: hoodriverheather ***@***.***>
Sent: Monday, July 22, 2024 9:56 AM
To: EDRN/labcas-ui ***@***.***>
Cc: Liu, David (US 3902-Affiliate) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [EDRN/labcas-ui] Modify text on login screen for Forgot password link (Issue #217)


@yuliujpl<https://urldefense.us/v3/__https://github.com/yuliujpl__;!!PvBDto6Hs4WbVuu7!Iquy_U1LKvBhNXA7Vj4ag5KD9fEl2H0bzxHtzsuu2uG7un8CmiC3C7lsyCjR9Xy46w31iB0AuGJnTcmvn3TL9QORROBizA$> I don't see the updated login text under the Non-EDRN member on Prod.
Forgot<https://edrn-labcas.jpl.nasa.gov/biokey/edrn/forgotten/> your password to ready Forgot your password and/or your username.
Screenshot.2024-07-22.at.9.48.47.AM.png (view on web)<https://urldefense.us/v3/__https://github.com/user-attachments/assets/11e69034-4e12-4eb1-ad28-d88cfe1b6e37__;!!PvBDto6Hs4WbVuu7!Iquy_U1LKvBhNXA7Vj4ag5KD9fEl2H0bzxHtzsuu2uG7un8CmiC3C7lsyCjR9Xy46w31iB0AuGJnTcmvn3TL9QPgY0pDqg$>

I see it on Dev. Can you please push this update to Prod?
Screenshot.2024-07-22.at.9.48.22.AM.png (view on web)<https://urldefense.us/v3/__https://github.com/user-attachments/assets/4d46c1f4-f8fa-4c6e-9656-3afddbb2fc7f__;!!PvBDto6Hs4WbVuu7!Iquy_U1LKvBhNXA7Vj4ag5KD9fEl2H0bzxHtzsuu2uG7un8CmiC3C7lsyCjR9Xy46w31iB0AuGJnTcmvn3TL9QMVXa19hw$>

**Comment by yuliujpl** [comment]
Closing due to resolution of this
